# -*- coding: utf-8 -*-
"""Load yFinance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2t0rMdFsVLZRuICbw3O8MKrEcd4Khav

# 実装：ローカル用の株価データセットを構築する方法
東証プライム全銘柄の日足データ（2010年〜2025年）を .parquet 形式で保存し、
最終的に1つの統合ファイルとして使えるようにすることを目的とします。

この統合データは、後のスクリーニングや機械学習、PCAなどの分析に有用です。

## 全体の処理フロー
本稿のコードは下記の項目で構成されています：

- データ取得：銘柄ごとに15年分の日足データを .parquet で保存
- バッチ処理：保存された銘柄ファイルを 200 件ずつまとめて分割保存
- 統合処理：バッチファイルを結合して、1つの巨大な .parquet を作成
- 中身の確認：データの件数、カラム数、データ型、欠損の数を確認
- 有用性の確認：統合データから個別銘柄を抽出・可視化する

### ① yfinanceで全銘柄の株価を .parquet に保存
"""

!pip install curl_cffi --quiet

# Driveマウントとライブラリ
from google.colab import drive
drive.mount('/content/drive')

# 保存先（必要に応じて変更）
output_dir = '/content/drive/MyDrive/stock_prediction/ver.1/results/2025-06-27'
output_raw_dir = output_dir + '/raw'
os.makedirs(output_dir, exist_ok=True)
# 銘柄リスト読み込み(前回記事参照)
excel_path = "/content/drive/MyDrive/stock_prediction/external_sources/data_j.xls"

# バッチファイルのディレクトリ
input_dir = output_dir
batch_dir = os.path.join(input_dir, "batch_size")
os.makedirs(batch_dir, exist_ok=True)

# マージファイルのディレクトリ設定
output_parquet = output_dir + "/ticker_combined_OHLCV.parquet"

import yfinance as yf
import pandas as pd
import os
import time
from tqdm import tqdm
from curl_cffi import requests
from datetime import datetime, timedelta
session = requests.Session(impersonate="safari15_5")

def get_latest_date_from_parquet(file_path):
    """既存のparquetファイルから最新の日付を取得"""
    try:
        if not os.path.exists(file_path):
            return None
        # Date列のみ読み込んでメモリ効率を向上
        df_dates = pd.read_parquet(file_path, columns=['Date'])
        if df_dates.empty:
            return None
        return df_dates['Date'].max()
    except Exception as e:
        print(f"⚠️ {file_path} から日付読み込みエラー: {e}")
        # 破損ファイルの場合、バックアップしてNoneを返す
        try:
            backup_path = file_path + ".corrupted"
            if os.path.exists(file_path):
                os.rename(file_path, backup_path)
                print(f"🔄 破損ファイルをバックアップ: {backup_path}")
        except:
            pass
        return None

def merge_and_save_data(existing_file, new_data, ticker):
    """既存データと新規データをマージして保存"""
    try:
        if os.path.exists(existing_file):
            # 既存データを読み込み
            existing_data = pd.read_parquet(existing_file)
            # 新規データと結合
            combined_data = pd.concat([existing_data, new_data], ignore_index=True)
            # 重複削除（日付ベース、新しいデータを優先）
            combined_data.drop_duplicates(subset=['Date'], keep='last', inplace=True)
            # 日付順でソート
            combined_data.sort_values(by='Date', inplace=True)
            combined_data.reset_index(drop=True, inplace=True)
        else:
            combined_data = new_data
        
        # 保存
        combined_data.to_parquet(existing_file, index=False)
        return len(new_data)
    except Exception as e:
        print(f"❌ {ticker} マージエラー: {e}")
        return 0

# 差分更新モードかどうかを判定
INCREMENTAL_UPDATE = True  # False にすると全期間ダウンロード

df_all = pd.read_excel(excel_path)
df_all = df_all[df_all["市場・商品区分"] == "プライム（内国株式）"]
df_all["Ticker"] = df_all["コード"].astype(str).str.zfill(4) + ".T"
df_list = df_all[["Ticker", "33業種コード"]].copy()

# 統計情報
stats = {"total": len(df_list), "updated": 0, "new_data_points": 0, "errors": 0}

# 各銘柄のデータを取得して parquet 形式で保存
for _, row in tqdm(df_list.iterrows(), total=len(df_list)):
    ticker = row["Ticker"]
    industry_code = row["33業種コード"]
    ticker_file = os.path.join(output_raw_dir, f"{ticker}_OHLCV.parquet")

    try:
        # 差分更新モードの場合、既存データの最新日付を確認
        if INCREMENTAL_UPDATE:
            latest_date = get_latest_date_from_parquet(ticker_file)
            if latest_date:
                # 最新日付の翌日から今日までをダウンロード
                start_date = (latest_date + timedelta(days=1)).strftime("%Y-%m-%d")
                end_date = datetime.now().strftime("%Y-%m-%d")
                
                # 最新日付が今日以降の場合はスキップ
                if latest_date.date() >= datetime.now().date():
                    print(f"{ticker} ⏭️ 最新データです（{latest_date.strftime('%Y-%m-%d')}）")
                    continue
                    
                print(f"{ticker} 📅 差分更新: {start_date} → {end_date}")
            else:
                # 既存ファイルがない場合は全期間ダウンロード
                start_date = "2010-01-01"
                end_date = "2025-06-27"
                print(f"{ticker} 🆕 新規ダウンロード: {start_date} → {end_date}")
        else:
            # 全期間ダウンロード
            start_date = "2010-01-01"
            end_date = "2025-06-27"
            print(f"{ticker} 🔄 全期間ダウンロード: {start_date} → {end_date}")

        # yfinanceでデータダウンロード
        df = yf.download(ticker, start=start_date, end=end_date, auto_adjust=False, session=session)
        
        if df.empty:
            print(f"{ticker} ⚠️ データなし（上場廃止/期間外）")
            continue
            
        # 新規データが少ない場合の処理
        if len(df) < 5 and INCREMENTAL_UPDATE and latest_date:
            print(f"{ticker} ⚠️ 新規データが少ない（{len(df)}件）")
            
        # データの整形
        df.reset_index(inplace=True)
        df = df.astype({
            "Open": "float64", "High": "float64", "Low": "float64",
            "Close": "float64", "Adj Close": "float64", "Volume": "int64"
        })
        df["Date"] = pd.to_datetime(df["Date"])
        df["Ticker"] = ticker
        df["IndustryCode"] = int(industry_code)

        # カラム名の正規化
        df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
        
        # データマージ・保存
        if INCREMENTAL_UPDATE:
            new_data_count = merge_and_save_data(ticker_file, df, ticker)
            stats["new_data_points"] += new_data_count
            print(f"{ticker} ✅ {new_data_count}件追加")
        else:
            df.to_parquet(ticker_file, index=False)
            stats["new_data_points"] += len(df)
            print(f"{ticker} ✅ {len(df)}件保存")
            
        stats["updated"] += 1
        time.sleep(1)  # 1秒の待機（アクセス制限回避）

    except Exception as e:
        print(f"{ticker} ❌ failed: {e}")
        stats["errors"] += 1
        
        # 連続エラーの場合、長めの待機時間を設定
        if stats["errors"] > 5:
            print("⏱️ 連続エラーのため5秒待機...")
            time.sleep(5)

# 実行統計の表示
print("\n" + "="*50)
print("📊 実行統計")
print("="*50)
print(f"総銘柄数: {stats['total']}")
print(f"更新済み: {stats['updated']}")
print(f"新規データ: {stats['new_data_points']:,} 件")
print(f"エラー: {stats['errors']}")
print(f"成功率: {(stats['updated'] / stats['total'] * 100):.1f}%")
print("="*50)

"""### ② バッチ処理
株価データは銘柄数が多く、期間も長いため、すべてを一気に読み込むとメモリを圧迫しやすくなります。1600銘柄を一度に統合させても、進む場合もありますが、何回かクラッシュしたことがあります。
そこで、ファイルをあらかじめ200件ずつにまとめておく（バッチ化）ことで、

- メモリ負荷を軽減
- 並列処理や検証を柔軟に行える
- 後の統合処理が安定する

ことが期待できます。このコードの流れは下記の通りです。

- 保存ディレクトリ内の .parquet を一覧取得
- 空データやエラーを除外しながら読み込み
- 200件ごとに batch_0.parquet, batch_1.parquet, ... として保存
"""

# 既存のバッチファイルを削除
for f in os.listdir(batch_dir):
    if f.startswith("batch_") and f.endswith(".parquet"):
        os.remove(os.path.join(batch_dir, f))
print(" 古いバッチファイルを削除しました")

# .parquetファイル一覧（batch_除外、raw/サブディレクトリ内のファイルを対象）
parquet_files = []
if os.path.exists(output_raw_dir):
    parquet_files = sorted([
        f for f in os.listdir(output_raw_dir)
        if f.endswith(".parquet")
    ])
else:
    # 旧形式（rawディレクトリがない場合）
    parquet_files = sorted([
        f for f in os.listdir(input_dir)
        if f.endswith(".parquet") and not f.startswith("batch_")
    ])

# バッチ処理（200件ごとに保存）
batch_size = 200
for i in tqdm(range(0, len(parquet_files), batch_size), desc=" バッチ保存中"):
    batch_files = parquet_files[i:i + batch_size]
    dfs = []
    for file in batch_files:
        try:
            # rawディレクトリ内のファイルを読み込み
            file_path = os.path.join(output_raw_dir, file) if os.path.exists(output_raw_dir) else os.path.join(input_dir, file)
            df = pd.read_parquet(file_path)
            if not df.empty:
                dfs.append(df)
            else:
                print(f"⚠️ 空データスキップ: {file}")
        except Exception as e:
            print(f"❌ 読み込み失敗: {file}, 理由: {e}")

    if dfs:
        df_batch = pd.concat(dfs, ignore_index=True)
        batch_path = os.path.join(batch_dir, f"batch_{i // batch_size}.parquet")
        df_batch.to_parquet(batch_path, index=False)
        print(f"✅ batch_{i // batch_size} バッチリsaved")
    else:
        print(f"🚫 batch_{i // batch_size} はスキップ（全データ空）")

"""### ③ バッチファイルを1つの統合 .parquet にまとめる
前のステップで保存した batch_0.parquet, batch_1.parquet, ... といったバッチファイルをすべて読み込み、1つの巨大な .parquet ファイルに統合します。

これが最終的な「全銘柄・全期間データ」の完成版になります。

#### 処理の流れ
- batch_size/ フォルダ内のファイルをすべて読み込む
- 中身を1つの DataFrame にまとめる
- ticker_combined_OHLCV.parquet として保存
"""

# バッチファイル一覧を取得
batch_files = sorted([f for f in os.listdir(batch_dir) if f.endswith(".parquet")])

# バッチを順に読み込み＆統合
df_list = []
for file in tqdm(batch_files, desc=" 統合中"):
    path = os.path.join(batch_dir, file)
    df = pd.read_parquet(path)
    df_list.append(df)

# 結合して1つのファイルに保存
df_combined = pd.concat(df_list, ignore_index=True)
df_combined.to_parquet(output_parquet, index=False)

print(f"\n 統合完了: {output_parquet}")

"""### ④：統合済みデータの読み込みと確認
前ステップで作成した ticker_combined_OHLCV.parquet を読み込み、
中身を確認して問題がないかチェックします。

- 統合後のデータが正しく読み込めるか確認
- カラム構成、欠損、データ型、件数などを検証

出力

- 件数：568万行超 → おおよそ2000銘柄×約2800営業日（想定どおり）
- カラム数：9列 → OHLCV＋識別情報（ティッカー、業種コード）
- データ型：すべて適切に指定されており、後の処理もスムーズ
- 欠損：なし（理想の状態）
"""

# データ読み込み
df = pd.read_parquet(output_parquet, engine="pyarrow")

# 中身の確認
print("ファイル:", output_parquet)
print("shape:", df.shape)
print("columns:", df.columns.tolist())
print("dtypes:\n", df.dtypes)
print("null counts:\n", df.isnull().sum())
print("head:\n", df.head())

"""### ⑤：統合データから個別銘柄を抽出・可視化する
統合済みファイルから、特定の銘柄（例：7203.T）のデータを抽出し、株価の推移を可視化ができるか確認します。

#### 処理の流れ
- 統合ファイルを読み込む
- "Date" を時系列インデックスに変換（yfinance風）
- 任意のティッカー（ここでは "7203.T"）でフィルタ
- 株価の推移を可視化＋リターンを計算して列追加
"""

import pandas as pd
import os
import matplotlib.pyplot as plt

# 統合ファイルの読み込み
df = pd.read_parquet(output_parquet, engine="pyarrow")
df["Date"] = pd.to_datetime(df["Date"])  # 念のため型変換
df.set_index("Date", inplace=True)       # yfinance形式っぽくする

# 特定銘柄（例：7203.T）だけを抽出して昇順に並べる
df_7203 = df[df["Ticker"] == "7203.T"].sort_index()
print(df_7203.head())

# 1日リターンを追加（Closeベース）
df_7203["Return_1d"] = df_7203["Close"].pct_change()

# 株価推移を可視化
df_7203["Close"].plot(title="7203.T - Close Price", figsize=(10, 4))
plt.grid(True)
plt.show()

"""## まとめ
本スクリプトでは、東証プライム全銘柄の株価データを yfinance から取得し、.parquet 形式で保存・整理する一連の処理を構築しました。

- 銘柄ごとのデータを .parquet で個別保存
- メモリ効率を考慮して200件ずつバッチに分割
- 全バッチを統合して1つのマスターファイルを作成
- 特定銘柄の抽出・時系列処理・可視化まで確認
"""